app:
  root:
    url: e-taskify/api/v1
  default:
    user:
      password: test123



spring:
  datasource:
    url: jdbc:localhost://Postgres:5432/postgre
    password: admin
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  h2:
  #    console:
  #      path: /h2
  #      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: eTaskifySecretKey!@#123
  expiration: 7_200_000
  header: Authorization
  route:
    authentication:
      path: auth